cuda: True
inference: False
samples_per_graph: 10
ckpt_load: ''
data:
        train_data: 'dataset_graph_pred_train.pkl'
        test_data: 'dataset_graph_pred_test.pkl'
log:
        print_every: 20
        print_long_every: 50
        delete_prior_logs: False
        save_every: 10
train:
        epochs: 500
        batch_size: 8
        num_workers: 8
        lr: 0.0001
        overfit: False
        agents: 'all'
        loss_close: 1.0
        loss_goal: 1.0
        loss_weighted_edge: True
test:
        num_iters: 20
model:
        predict_last: True
        predict_edge_change: True
        reduced_graph: True
        edge_pred: 'concat'
        edge_types: 5
        max_nodes: 70
        max_class_objects: 37
        max_actions: 10
        num_states: 4
        num_attributes: 6
        hidden_size: 100
        max_tsteps: 50
        goal_inp: False
        gated: False
        agent_embed: False
        num_agents: 100
        relative_coords: False
        time_aggregate: 'LSTM' #
        state_encoder: 'TF' # GNN
