defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

data_ratio: 1.0
cuda: True
logging: True
name_log: ''
inference: False
save_inference: False
plot_inference: False
inference_sample: False
inference_posterior: True
samples_per_graph: 2
ckpt_load: ''
data:
        train_data: 'dataset_graph_full_150step_larger_train.pkl' # 'dataset_graph_pred_train.pkl' dataset_graph_full_150step_larger_train.pkl
        test_data: 'dataset_graph_full_150step_larger_test.pkl' # 'dataset_graph_pred_test.pkl'
log:
        print_every: 10
        print_long_every: 50
        delete_prior_logs: False
        save_every: 10
train:
        epochs: 300
        batch_size: 64
        num_workers: 16
        lr: 0.0001
        overfit: False
        agents: 'all'
        loss_close: 1.0
        loss_goal: 1.0
        loss_weighted_edge: False
test:
        num_iters: 20
model:
        use_only_input: True
        condense_walking: True
        exclusive_edge: True # Whether to predict edges or container relations
        predict_last: True
        predict_diff: False
        predict_edge_change: False
        predict_node_change: False
        input_goal: True
        reduced_graph: False
        global_repr: 'pool'
        edge_pred: 'concat'
        edge_types: 4
        max_nodes: 70
        max_class_objects: 37
        max_actions: 10
        num_states: 4
        num_counts: 9
        num_task_preds: -1
        num_attributes: 6
        hidden_size: 100
        z_dim: 128
        kl_coeff: 1
        max_tsteps: 75 #50
        supervise_alltask: False
        goal_inp: False
        gated: False
        agent_embed: False
        num_agents: 100
        relative_coords: False
        input_vae: 'task' # 'graph/task/none'
        time_aggregate: 'LSTM' # LSTM, none, firstcurr, fcVAE, seqVAE
        cond_prior: True
        zvec: 'node' # node / single
        state_encoder: 'TF' # GNN/FC
        autoencoder_type: 'pure_autoencoder'
        predict_category: True
        predict_diff_preds: True
        kl_annealing: True
        kl_anneal_epoch: 60

