defaults:
        - agent_pred_graph: config_default_toy_excl

executable_file: ""
max_episode_length: 100
num_per_apartment: 20
dataset_path: ""
obs_type: "full"
mode: ""
record_dir: ""
base_port: 8080
use_editor: False
num_processes: 10
num_samples: 10
