log:
        print_every: 10
        print_long_every: 50
train:
        epochs: 50
        batch_size: 8
        num_workers: 10
        lr: 0.01
        overfit: True
model:
        max_nodes: 150
        max_class_objects: 37
        max_actions: 10
        num_states: 4
        num_attributes: 6
        hidden_size: 200
        max_tsteps: 100

