defaults:
        - agent_pred_graph: config_default_large_excl
executable_file: "/data/vision/torralba/frames/data_acquisition/SyntheticStories/website/release/simulator/v2.0/online_wah/online_wah_exec_2/linux_exec.online_wah_2.x86_64"
max_episode_length: 250
num_per_apartment: 20
dataset_path: ""
obs_type: "full"
mode: ""
record_dir: ""
base_port: 8080
use_editor: False
num_processes: 10
num_samples: 10
alpha: 1.0
beta: 1.0
max_benefit: 20.0

